# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 04:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
