# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 15:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_auto_20160328_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='publish_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 5, 15, 55, 19, 606558, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='course.Course'),
        ),
    ]
