# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_auto_20160405_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_datetime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='open_signup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='register_code',
            field=models.CharField(max_length=12),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
