# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-02 10:35
from __future__ import unicode_literals

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20160504_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, upload_to=course.models.resource_file_name),
        ),
    ]
