# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-03 08:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0019_auto_20160930_0416'),
        ('course', '0006_course_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competition.Competition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 3, 8, 26, 41, 753403, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
