# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-03 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20161103_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='register_code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
