# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20161109_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='invisible',
            field=models.BooleanField(default=False),
        ),
    ]
