# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_course_invisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tutor_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
