# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_competition_final_submit_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='final_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='final_submission',
            field=models.FilePathField(blank=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='evaluation',
            field=models.CharField(choices=[('AUC', 'Area Under ROC Curve'), ('RMSE', 'Root of Mean Square Error'), ('PRECISION', 'Precision'), ('RECALL', 'Recall'), ('ACCURACY', 'Accuracy'), ('MAP', 'Mean Average Precision'), ('NDCG', 'Normalized Discounted Cumulative Gain'), ('SMP', 'SMP cup 2016')], max_length=10),
        ),
    ]
