# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_auto_20160617_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='final_score',
            field=models.FloatField(blank=True),
        ),
    ]
