# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_auto_20160617_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='final_submission',
            new_name='final_submission_name',
        ),
        migrations.AddField(
            model_name='team',
            name='final_submission_path',
            field=models.FilePathField(blank=True),
        ),
    ]
