# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 09:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_competition_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='data_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='introduction_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='rules_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='slug_en',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
