# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-02 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0012_auto_20160802_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='slug_en',
        ),
    ]
