# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 07:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0013_remove_detail_slug_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='winner_week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField()),
                ('team_name', models.CharField(max_length=255)),
                ('leader_name', models.CharField(max_length=255)),
                ('single', models.IntegerField()),
                ('members', models.TextField(null=True)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='competition',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='winner_week',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Competition'),
        ),
        migrations.AddField(
            model_name='winner_week',
            name='leader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='winner_week',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Team'),
        ),
    ]
