# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0014_auto_20160808_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winner_week',
            old_name='leader_id',
            new_name='leader',
        ),
        migrations.RenameField(
            model_name='winner_week',
            old_name='team_id',
            new_name='team',
        ),
    ]
