# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-22 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0016_competition_finalcaculate_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='final_showscore_min',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='competition',
            name='final_showwinners_count',
            field=models.IntegerField(default=50),
        ),
    ]
