# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-13 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0019_auto_20160930_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='final_num_line',
            field=models.IntegerField(null=True),
        ),
    ]
