# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0020_competition_final_num_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='valid_end_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
