# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0021_competition_valid_end_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='invisible',
            field=models.BooleanField(default=False),
        ),
    ]
