# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-09 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0022_competition_invisible'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='week_winnernum',
            field=models.IntegerField(default=1),
        ),
    ]
