# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0023_competition_week_winnernum'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='winner_end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='winner_start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
