# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0024_auto_20170310_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='filetype',
            field=models.CharField(default='csv', max_length=10),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
