# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0026_sub_limt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_limt',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='sub_limt',
            name='start_time',
        ),
    ]
