# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-12 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0027_auto_20170312_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='evaluation',
            field=models.CharField(choices=[('AUC', 'Area Under ROC Curve'), ('RMSE', 'Root of Mean Square Error'), ('PRECISION', 'Precision'), ('RECALL', 'Recall'), ('ACCURACY', 'Accuracy'), ('MAP', 'Mean Average Precision'), ('NDCG', 'Normalized Discounted Cumulative Gain'), ('SMP', 'SMP cup 2016'), ('SOHU', 'Sohu Luckydata')], max_length=10),
        ),
    ]
