# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0029_competition_evaluate_reverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='award',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
