# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20151129_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodification',
            name='action',
            field=models.IntegerField(choices=[(1, 'activation'), (2, 'reset password'), (3, 'join team')]),
        ),
    ]
