# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-15 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160729_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='real_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
