# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-18 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userinfo_remote_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_visit',
            field=models.DateTimeField(null=True),
        ),
    ]
