# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-27 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userinfo_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='organization',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
