# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_usermodifyprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodifyprofile',
            old_name='mode_after',
            new_name='modify_after',
        ),
        migrations.RenameField(
            model_name='usermodifyprofile',
            old_name='mod_before',
            new_name='modify_before',
        ),
    ]
